on: push
name: Emmanuel Asinyo
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.0
      with:
        ftp-server: ftp://ftp.asinyo.ca/
        ftp-username: easinyo_admin
        ftp-password: ${{ secrets.FTP_PASSWORD }}
